"""Small exact linear-algebra primitives over GF(3)."""

from __future__ import annotations

from numbers import Integral
from typing import Iterable

Vector = tuple[int, ...]
Matrix = tuple[Vector, ...]


def scalar(value: int) -> int:
    """Return an exact GF(3) scalar."""
    if isinstance(value, bool) or not isinstance(value, Integral):
        raise TypeError("GF(3) values must be integers")
    return int(value) % 3


def vector(values: Iterable[int], *, width: int | None = None) -> Vector:
    """Normalize an iterable to an immutable GF(3) vector."""
    result = tuple(scalar(value) for value in values)
    if width is not None and len(result) != width:
        raise ValueError(f"expected vector width {width}, got {len(result)}")
    return result


def matrix(rows: Iterable[Iterable[int]]) -> Matrix:
    """Normalize rows and require a rectangular, non-empty matrix."""
    result = tuple(vector(row) for row in rows)
    if not result or not result[0]:
        raise ValueError("GF(3) matrix must be non-empty")
    width = len(result[0])
    if any(len(row) != width for row in result):
        raise ValueError("GF(3) matrix must be rectangular")
    return result


def add(left: Vector, right: Vector) -> Vector:
    """Add equal-width vectors over GF(3)."""
    if len(left) != len(right):
        raise ValueError("GF(3) vector widths differ")
    return tuple((a + b) % 3 for a, b in zip(left, right))


def negate(values: Vector) -> Vector:
    """Return the additive inverse over GF(3)."""
    return tuple((-value) % 3 for value in values)


def rank(rows: Iterable[Iterable[int]]) -> int:
    """Compute exact row rank by Gaussian elimination over GF(3)."""
    work = [list(vector(row)) for row in rows]
    if not work:
        return 0
    width = len(work[0])
    if any(len(row) != width for row in work):
        raise ValueError("GF(3) matrix must be rectangular")

    pivot_row = 0
    for column in range(width):
        pivot = next(
            (row for row in range(pivot_row, len(work)) if work[row][column]),
            None,
        )
        if pivot is None:
            continue
        work[pivot_row], work[pivot] = work[pivot], work[pivot_row]
        inverse = 1 if work[pivot_row][column] == 1 else 2
        work[pivot_row] = [(inverse * value) % 3 for value in work[pivot_row]]

        for row, values in enumerate(work):
            if row == pivot_row or values[column] == 0:
                continue
            factor = values[column]
            work[row] = [
                (value - factor * base) % 3
                for value, base in zip(values, work[pivot_row])
            ]
        pivot_row += 1
        if pivot_row == len(work):
            break
    return pivot_row


def in_row_span(values: Vector, rows: Matrix) -> bool:
    """Return whether ``values`` is generated by ``rows`` over GF(3)."""
    if len(values) != len(rows[0]):
        raise ValueError("vector and matrix widths differ")
    return rank(rows + (values,)) == rank(rows)
